### ISSUE TITLE
About that clicker game...

### ISSUE THREAD

**Issue by fasterthanlime** [supertasball/supertasball#1]
**Please vote by adding a :+1: or :-1: reaction to the comment**

I think we have to make a choice here:

## Option :+1:  : Expand the clicker part

The original goal behind the clicker part of the game was to develop your economy - to start small, and eventually be able to buy upgrades that make it easier to develop better programs (even going back to previous courses).

In the jam version however:

  * Mine satoshi is just a dumb crypto joke and should be removed
  * Sealing a car is OP (and a permadeath joke), it should be removed
  * It's sort of too easy to grind by washing windows / mowing lawns, I feel like these should "deplete" after a while, and be replaced with other activites, or just removed altogether?
  * There are no idle options - it's all just clicking. In my original ideas, there would've been things you could "build" that would give you money over time, so gameplay is spread out throughout hours/days :)

## Option :-1: : Strip the clicker part

Strip all the grinding mechanics, do not invest any time in adding idle mechanics, just have it be a pure set of levels that unlock when you complete other levels, just keep the upgrades maybe? (Or just a highscore table?)

**Please vote by adding a :+1: or :-1: reaction to the comment**

**Comment by Henry-Gale** [comment]
👎

**Comment by fasterthanlime** [comment]
The community has voted!

  * 6 in favor of removing the clicker game
  * 1 in favor of keeping it

And so I have removed it :)
