### ISSUE TITLE
Print a message about mining satoshi in the console

### ISSUE THREAD

**Issue by connorshea** [supertasball/supertasball#9]
I feel like, in order to really give the vibe that I'm mining cryptocurrency, you should log something in the console when I press the "Mine satoshi" button. The loading icon isn't good enough for 1337 hackers like me, who know to look in the console to see whether the game is actually mining coins.

**Comment by fasterthanlime** [comment]
I personally would want to remove it :) It's under community vote here: https://github.com/supertasball/supertasball/issues/1

**Comment by fasterthanlime** [comment]
Closing because the clicker part has been removed
